name: Build-Test-Lint-etc (linux)

on: [push]

permissions: write-all

jobs:

  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: flake8 Lint
        uses: TrueBrain/actions-flake8@v2
        with:
          plugins: Flake8-pyproject==1.2.3 flake8-docstrings==1.7.0 flake8-quotes==3.3.2 flake8-bugbear==23.9.16 flake8-mock==0.4 flake8-tuple==0.4.1
          # only_warn: 1  #causes action to always be succesful, but still provide annotations

  test:    
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10"]
#        python-version: [3.8, 3.9, 3.10, 3.11]
    steps:    
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - run: |
        ./ci/win32/create_venv.cmd
        ./ci/win32/install_dependencies.cmd
    - name: run unit tests
      run: |
        ./ci/win32/test_unit.cmd
    - name: Surface failing tests
      if: always()
      uses: pmeier/pytest-results-action@main
      with:
        # A list of JUnit XML files, directories containing the former, and wildcard
        # patterns to process.
        # See @actions/glob for supported patterns.
        path: test-results.xml

        # Add a summary of the results at the top of the report
        # Default: true
        summary: true

        # Select which results should be included in the report.
        # Follows the same syntax as
        # `pytest -r`
        # Default: fEX
        display-options: fEX

        # Fail the workflow if no JUnit XML was found.
        # Default: true
        fail-on-empty: true

  typecheck:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10"]
#        python-version: [3.8, 3.9, 3.10, 3.11]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - run: |
        ./ci/win32/create_venv.cmd
        ./ci/win32/install_dependencies.cmd

    - name: Add mypy annotator
      uses: pr-annotators/mypy-pr-annotator@v1.0.0

    - name: run typechecker
      run: |
        ./ci/win32/typecheck.cmd
  build:
    name: Build the python package
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - run: |
          ./ci/win32/create_venv.cmd
          ./ci/win32/install_dependencies.cmd

      - name: build
        run: |
          ./ci/win32/build_python_package.sh