name: Build-Test-Lint-etc (Windows)

on: [push]

permissions: write-all

jobs:
  ruff-lint:
    runs-on: windows-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Ruff lint
        run: uv run ruff check ./src/pywandahydra

  test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    #        python-version: [3.8, 3.9, 3.10, 3.11]
    steps:
      - uses: actions/checkout@v3
      - name: Make script executable
        run: |
          chmod +x ./ci/windows/create_venv.bat
          chmod +x ./ci/windows/install_dependencies.bat
          chmod +x ./ci/windows/test_unit.bat
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - run: |
          ./ci/windows/create_venv.bat
          ./ci/windows/install_dependencies.bat
      - name: run unit tests
        run: |
          ./ci/windows/test_unit.bat
      - name: Surface failing tests
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          # A list of JUnit XML files, directories containing the former, and wildcard
          # patterns to process.
          # See @actions/glob for supported patterns.
          path: test-results.xml

          # Add a summary of the results at the top of the report
          # Default: true
          summary: true

          # Select which results should be included in the report.
          # Follows the same syntax as
          # `pytest -r`
          # Default: fEX
          display-options: fEX

          # Fail the workflow if no JUnit XML was found.
          # Default: true
          fail-on-empty: true

  typecheck:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    #        python-version: [3.8, 3.9, 3.10, 3.11]
    steps:
      - uses: actions/checkout@v3
      - name: Make script executable
        run: |
          chmod +x ./ci/windows/create_venv.bat
          chmod +x ./ci/windows/install_dependencies.bat
          chmod +x ./ci/linux/typecheck.sh
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - run: |
          ./ci/linux/create_venv.sh
          ./ci/linux/install_dependencies.sh

      - name: Add mypy annotator
        uses: pr-annotators/mypy-pr-annotator@v1.0.0

      - name: run typechecker
        run: |
          ./ci/linux/typecheck.sh

  build:
    name: Build the python package
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Make script executable
        run: |
          chmod +x ./ci/windows/create_venv.bat
          chmod +x ./ci/windows/install_dependencies.bat
          chmod +x ./ci/windows/build_python_package.bat
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - run: |
          ./ci/windows/create_venv.bat
          ./ci/windows/install_dependencies.bat

      - name: build
        run: |
          ./ci/linux/build_python_package.sh
